version: '3.5'

services:
    django_boilerplate: 
        image: 192.168.0.121:5555/django_swarm
        ports:
            - 8000:8000
        environment:
            - APP_ENVIRONMENT=staging
            - SECRET_KEY_VALUE=bDf%Ma*y8HX6S2zZVMP37bbWc^zLT#jwDTFMP7hZFZvWczeD5@
            - DEBUG_VALUE=true
            - ALLOWED_HOSTS_VALUE=*
            - DATABASE_NAME_VALUE=django_boilerplate
            - DATABASE_USER_FILE=/run/secrets/pdb_username
            - DATABASE_PASSWORD_FILE=/run/secrets/pdb_password
            - DATABASE_HOSTNAME_VALUE=db
            - DATABASE_PORT_VALUE=5432
        secrets:
            - pdb_password
            - pdb_username
        depends_on:
            - db
        networks:
            - internal_db
            - reverse_proxy
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == app

    db:
        image: postgres:11.1
        environment:
            - POSTGRES_USER_FILE=/run/secrets/pdb_username
            - POSTGRES_PASSWORD_FILE=/run/secrets/pdb_password
            - POSTGRES_DB=django_boilerplate
        secrets:
            - pdb_password
            - pdb_username
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - internal_db
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == app

    reverseproxy:
        image: nginx:1.15-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./tools/ssl:/etc/ssl
            - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - django_boilerplate
        networks:
            - reverse_proxy
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == app

volumes:
    db-data:

networks:
    internal_db:
    reverse_proxy:

secrets:
    pdb_password:
      external: true
    pdb_username:
      external: true
