version: '3.5'

services:
    ds-db-dev:
        image: postgres:11.1
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres-admin
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=django_sample
        volumes:
            - ds-db-data-dev:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    ds-db-data-dev:

