name: Deploy website
"on":
push:
  branches: bhavitha-deployment-script
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Latest code
        uses: actions/checkout@v3
        with:
          server: http://dcm.uhcl.edu/caps23g2
          username: sce\caps23g2
          password: Capstonegroup2
