name: Deploy website
"on":
  push:
    branches:
      - bhavitha-deployment-script
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Latest code
        uses: actions/checkout@v3
        with:
          ftp-server: ftp://dcm.uhcl.edu/caps23g2
          ftp-username: sce\caps23g2
          ftp-password: Capstonegroup2
