"on":
  push:
    branches:
      - bhavitha-deployment-script

name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: latest code
        uses: actions/checkout@v3

      - name: directory
        run: cd ./project-portfolio

      - name: Build Project
        run: npm i && ng serve && ng build --base-href /caps23g2/ && ng build --base-href /caps23g2/project_portfolio/

      - name: File
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp://dcm.uhcl.edu
          server-dir: ftp://dcm.uhcl.edu/pages/
          local-dir: ./ai-score-2-music/project_portfolio/dist/project_portfolio/
          username: sce\caps23g2
          password: ${{ secrets.ftp_password }}
