name: Deploy website
"on":
push:
branches: -master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp://dcm.uhcl.edu/caps23g2
          username: sce\caps23g2
          password: Capstonegroup2
